# Generated by Django 6.0.2 on 2026-02-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('ph', 'pH'), ('tds', 'TDS'), ('temp', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('severity', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sensor_alert',
            },
        ),
    ]
