# Generated by Django 6.0.2 on 2026-02-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='recommendation',
            field=models.TextField(default=None, null=True),
        ),
    ]
