# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alert_recommendation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='alert',
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.alert')),
            ],
            options={
                'db_table': 'alert_notifications',
            },
        ),
    ]
