# Generated by Django 6.0.2 on 2026-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_alert_table_alertnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notified_critical',
            field=models.BooleanField(default=False),
        ),
    ]
