# Generated by Django 6.0.2 on 2026-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alert_notified_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
