# Generated by Django 6.0.2 on 2026-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alertnotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='recommendation',
            field=models.JSONField(default=None, null=True),
        ),
    ]
