# Generated by Django 6.0.2 on 2026-03-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_alter_alert_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='critical_count',
            field=models.IntegerField(default=0),
        ),
    ]
