# Generated by Django 6.0.2 on 2026-03-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_alert_critical_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_epoch', models.BigIntegerField()),
                ('last_received_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
