# Generated by Django 6.0.2 on 2026-03-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_systemstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemstatus',
            table='system_status',
        ),
    ]
