# Generated by Django 6.0.2 on 2026-03-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_systemhealthevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealthevent',
            name='elapsed',
            field=models.BigIntegerField(default=0),
        ),
    ]
