# Generated by Django 6.0.2 on 2026-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0011_systemhealthevent_elapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemhealthevent',
            name='message',
        ),
        migrations.AddField(
            model_name='systemhealthevent',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='systemhealthevent',
            table='system_event',
        ),
    ]
