# Generated by Django 6.0.2 on 2026-03-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_remove_systemhealthevent_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemhealthevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
