# Generated by Django 6.0.2 on 2026-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0013_alter_systemhealthevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='sensor',
            field=models.CharField(choices=[('ph', 'pH'), ('tds', 'TDS'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20),
        ),
    ]
