# Generated by Django 6.0.2 on 2026-03-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0014_alter_alert_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='has_sent_intial',
            field=models.BooleanField(default=False),
        ),
    ]
