# Generated by Django 6.0.1 on 2026-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_raw', models.FloatField()),
                ('ph_clean', models.FloatField()),
                ('tds_raw', models.IntegerField()),
                ('tds_clean', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
    ]
