# Generated by Django 6.0.1 on 2026-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='epoch',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.IntegerField(),
        ),
    ]
