# Generated by Django 6.0.1 on 2026-02-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sensorreading_is_live_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
