# Generated by Django 6.0.1 on 2026-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(unique=True)),
                ('ph_clean', models.FloatField()),
                ('tds_clean', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorReadingRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(unique=True)),
                ('ph_raw', models.FloatField()),
                ('tds_raw', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
