# Generated by Django 6.0.1 on 2026-02-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedReading',
        ),
        migrations.DeleteModel(
            name='SensorReadingRaw',
        ),
    ]
