# Generated by Django 6.0.1 on 2026-02-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(unique=True)),
                ('ph_raw', models.FloatField()),
                ('ph_clean', models.FloatField(blank=True, null=True)),
                ('tds_raw', models.IntegerField()),
                ('tds_clean', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('datetime', models.CharField(verbose_name=50)),
            ],
            options={
                'ordering': ['epoch'],
                'indexes': [models.Index(fields=['epoch'], name='data_sensor_epoch_7ddc76_idx')],
            },
        ),
    ]
