# Generated by Django 6.0.1 on 2026-02-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='data_sensor_epoch_7ddc76_idx',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
